/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js; it is checked in so `tsc --noEmit`
// typechecks without a prior `next build`.
export {};