import type { Product } from "../types.js";

// 40 hackathon-sized products across the 4 allowed categories.
// A few carry stock:0 so the "offer an in-stock alternative" path is real
// and demonstrable. Do NOT add categories — the backend enforces the enum.
export type ProductSeed = Omit<Product, "id">;

export const SEED_PRODUCTS: ProductSeed[] = [
  // ---------------- Electronics ----------------
  {
    name: "Nova Wireless Earbuds",
    category: "Electronics",
    price: 2499,
    stock: 40,
    rating: 4.6,
    reviewCount: 1200,
    keySpecs: ["Bluetooth 5.3", "30h battery", "IPX5 splash-proof"],
    description: "Lightweight wireless earbuds with deep bass and a pocketable charging case.",
  },
  {
    name: "Pulse Smart Watch Pro",
    category: "Electronics",
    price: 4299,
    stock: 25,
    rating: 4.4,
    reviewCount: 843,
    keySpecs: ["1.9 inch AMOLED", "7-day battery", "Built-in GPS"],
    description: "Fitness and notification smart watch with a bright always-on display.",
  },
  {
    name: "Sona Bluetooth Speaker",
    category: "Electronics",
    price: 1999,
    stock: 60,
    rating: 4.3,
    reviewCount: 512,
    keySpecs: ["12W output", "10h playtime", "Waterproof"],
    description: "Portable speaker with punchy sound, made for indoor and outdoor use.",
  },
  {
    name: "Volt 10000mAh Power Bank",
    category: "Electronics",
    price: 1499,
    stock: 80,
    rating: 4.5,
    reviewCount: 934,
    keySpecs: ["20W fast charge", "Dual USB-C", "Slim design"],
    description: "A slim power bank that tops up two devices at once.",
  },
  {
    name: "Vision 4K TV Stick",
    category: "Electronics",
    price: 3199,
    stock: 0,
    rating: 4.2,
    reviewCount: 388,
    keySpecs: ["4K HDR", "Voice remote", "32GB storage"],
    description: "Plug-in streaming stick that turns any screen into a smart TV.",
  },
  {
    name: "Orbit Wireless Keyboard",
    category: "Electronics",
    price: 2799,
    stock: 20,
    rating: 4.4,
    reviewCount: 301,
    keySpecs: ["Backlit keys", "Low profile", "2.4GHz wireless"],
    description: "Quiet full-size keyboard with soft-touch keys and a battery that lasts months.",
  },
  {
    name: "EchoMesh Wi-Fi Router",
    category: "Electronics",
    price: 2199,
    stock: 45,
    rating: 4.1,
    reviewCount: 210,
    keySpecs: ["AC1200", "5 antennas", "Parental controls"],
    description: "Dual-band router that blankets a small home in reliable Wi-Fi.",
  },
  {
    name: "Aurora LED Desk Lamp",
    category: "Electronics",
    price: 1799,
    stock: 55,
    rating: 4.6,
    reviewCount: 676,
    keySpecs: ["3 color temperatures", "Touch dimmer", "USB charging port"],
    description: "An eye-friendly reading lamp with glare-free lighting for study or work.",
  },
  {
    name: "SoundWave USB Microphone",
    category: "Electronics",
    price: 3499,
    stock: 18,
    rating: 4.7,
    reviewCount: 442,
    keySpecs: ["Podcast quality", "Plug and play", "Headphone monitoring"],
    description: "A plug-and-play mic that makes calls, meetings, and recordings crystal clear.",
  },
  {
    name: "Nimbus Mini Projector",
    category: "Electronics",
    price: 8999,
    stock: 12,
    rating: 4.0,
    reviewCount: 168,
    keySpecs: ["HD 720p", "40-inch image", "Built-in speaker"],
    description: "A compact projector for cozy movie nights at home.",
  },

  // ---------------- Jewelry ----------------
  {
    name: "Silver Crescent Necklace",
    category: "Jewelry",
    price: 2499,
    stock: 15,
    rating: 4.8,
    reviewCount: 521,
    keySpecs: ["925 sterling silver", "45cm chain", "Hypoallergenic"],
    description: "A delicate silver crescent pendant on a fine chain, safe for sensitive skin.",
  },
  {
    name: "Pearl Drop Earrings",
    category: "Jewelry",
    price: 1799,
    stock: 30,
    rating: 4.5,
    reviewCount: 345,
    keySpecs: ["Cultured pearls", "Sterling silver posts", "Lightweight"],
    description: "Classic freshwater pearl drops that dress up anything.",
  },
  {
    name: "Gold-Plated Bangle Set",
    category: "Jewelry",
    price: 3299,
    stock: 22,
    rating: 4.3,
    reviewCount: 278,
    keySpecs: ["3 bangles", "18k gold plated", "Tarnish resistant"],
    description: "A stack of three polished gold-plated bangles with a satisfying weight.",
  },
  {
    name: "Onyx Bead Bracelet",
    category: "Jewelry",
    price: 999,
    stock: 40,
    rating: 4.6,
    reviewCount: 411,
    keySpecs: ["Natural onyx", "Stretch fit", "Unisex"],
    description: "A smooth matte-black bead bracelet you can slip on and forget.",
  },
  {
    name: "Sapphire Pendant Necklace",
    category: "Jewelry",
    price: 4499,
    stock: 10,
    rating: 4.7,
    reviewCount: 198,
    keySpecs: ["Lab sapphire", "18k plated chain", "Gift box included"],
    description: "A deep blue sapphire pendant on a long plated chain.",
  },
  {
    name: "Minimal Hoop Earrings",
    category: "Jewelry",
    price: 1199,
    stock: 50,
    rating: 4.4,
    reviewCount: 690,
    keySpecs: ["Feather light", "Tarnish-free finish", "Everyday wear"],
    description: "Round hoops so light you forget they are on.",
  },
  {
    name: "Rose Gold Ring Set",
    category: "Jewelry",
    price: 2899,
    stock: 14,
    rating: 4.5,
    reviewCount: 233,
    keySpecs: ["Stackable set", "Adjustable fit", "Rose gold tone"],
    description: "A set of three slim stackable rings in warm rose gold.",
  },
  {
    name: "Turquoise Stud Earrings",
    category: "Jewelry",
    price: 1599,
    stock: 0,
    rating: 4.2,
    reviewCount: 154,
    keySpecs: ["Turquoise inlay", "Sterling posts", "Small and neat"],
    description: "Crisp turquoise studs set in a simple silver base.",
  },
  {
    name: "Twisted Knot Anklet",
    category: "Jewelry",
    price: 1349,
    stock: 32,
    rating: 4.3,
    reviewCount: 187,
    keySpecs: ["Sterling silver", "Adjustable chain", "42 inch length"],
    description: "A fine twisted-chain anklet with a simple knot detail.",
  },
  {
    name: "Diamond-Cut Tennis Bracelet",
    category: "Jewelry",
    price: 5999,
    stock: 8,
    rating: 4.8,
    reviewCount: 302,
    keySpecs: ["Cubic zirconia", "Lobster clasp", "18k plated"],
    description: "A shimmering tennis bracelet that catches the light from every angle.",
  },

  // ---------------- Men's Clothing ----------------
  {
    name: "Classic Oxford Shirt",
    category: "Men's Clothing",
    price: 1499,
    stock: 40,
    rating: 4.4,
    reviewCount: 892,
    keySpecs: ["Soft cotton", "Wrinkle-free", "Regular fit"],
    description: "A wardrobe-staple oxford in a breathable, easy-care weave.",
  },
  {
    name: "Slim Denim Jeans",
    category: "Men's Clothing",
    price: 2199,
    stock: 28,
    rating: 4.5,
    reviewCount: 1210,
    keySpecs: ["Stretch denim", "5-pocket style", "Slim leg"],
    description: "Everyday jeans with just enough stretch to stay comfortable all day.",
  },
  {
    name: "Merino Crew Sweater",
    category: "Men's Clothing",
    price: 2799,
    stock: 20,
    rating: 4.6,
    reviewCount: 655,
    keySpecs: ["100% merino wool", "Warm but light", "Machine washable"],
    description: "A fine-gauge merino sweater that layers easily under a coat.",
  },
  {
    name: "Everyday Chino Pants",
    category: "Men's Clothing",
    price: 1899,
    stock: 35,
    rating: 4.3,
    reviewCount: 540,
    keySpecs: ["Tapered cut", "4 colors", "Machine washable"],
    description: "Sharp chinos that go from office to evening without a fuss.",
  },
  {
    name: "Lightweight Bomber Jacket",
    category: "Men's Clothing",
    price: 3299,
    stock: 15,
    rating: 4.4,
    reviewCount: 372,
    keySpecs: ["Water resistant", "Breathable shell", "2 zip pockets"],
    description: "A packable bomber that shrugs off light rain and wind.",
  },
  {
    name: "Cotton Crew T-Shirt 3-Pack",
    category: "Men's Clothing",
    price: 1099,
    stock: 60,
    rating: 4.2,
    reviewCount: 1430,
    keySpecs: ["100% combed cotton", "Set of 3", "Pre-shrunk"],
    description: "Three soft, sturdy crew tees that hold their shape wash after wash.",
  },
  {
    name: "Tailored Navy Blazer",
    category: "Men's Clothing",
    price: 5499,
    stock: 12,
    rating: 4.6,
    reviewCount: 210,
    keySpecs: ["Structured fit", "Horn buttons", "2-button closure"],
    description: "A sharp navy blazer that finishes a formal look.",
  },
  {
    name: "Fleece Hoodie",
    category: "Men's Clothing",
    price: 1799,
    stock: 45,
    rating: 4.3,
    reviewCount: 988,
    keySpecs: ["Brushed fleece", "Kangaroo pocket", "Drawstring hood"],
    description: "A heavyweight hoodie for cold mornings and lazy weekends.",
  },
  {
    name: "Linen Summer Shirt",
    category: "Men's Clothing",
    price: 1599,
    stock: 0,
    rating: 4.1,
    reviewCount: 456,
    keySpecs: ["Pure linen", "Breathable", "Long sleeve"],
    description: "A light, airy linen shirt made for warm weather.",
  },
  {
    name: "Jogger Sweatpants",
    category: "Men's Clothing",
    price: 1299,
    stock: 38,
    rating: 4.2,
    reviewCount: 610,
    keySpecs: ["Elastic waist", "Tapered leg", "Side pockets"],
    description: "Soft tapered joggers with a secure drawstring waist.",
  },

  // ---------------- Women's Clothing ----------------
  {
    name: "Floral Wrap Dress",
    category: "Women's Clothing",
    price: 2499,
    stock: 25,
    rating: 4.7,
    reviewCount: 830,
    keySpecs: ["Flattering wrap", "Side pockets", "Knee length"],
    description: "A flowy wrap dress with a tie waist and handy pockets.",
  },
  {
    name: "High-Rise Leggings",
    category: "Women's Clothing",
    price: 1399,
    stock: 50,
    rating: 4.5,
    reviewCount: 1560,
    keySpecs: ["Squat-proof", "4-way stretch", "High waist"],
    description: "Seamless-feel leggings that stay put through any workout.",
  },
  {
    name: "Silk Blouse",
    category: "Women's Clothing",
    price: 2099,
    stock: 22,
    rating: 4.6,
    reviewCount: 410,
    keySpecs: ["100% mulberry silk", "Pearl buttons", "Dry clean"],
    description: "A luxuriously smooth silk blouse with delicate pearl buttons.",
  },
  {
    name: "A-Line Floral Skirt",
    category: "Women's Clothing",
    price: 1799,
    stock: 26,
    rating: 4.4,
    reviewCount: 355,
    keySpecs: ["Midi length", "Hidden zip", "Lined"],
    description: "A twirlable midi skirt in a soft floral print.",
  },
  {
    name: "Wool Tailored Coat",
    category: "Women's Clothing",
    price: 6999,
    stock: 10,
    rating: 4.8,
    reviewCount: 264,
    keySpecs: ["Structured wool", "Double breasted", "Long length"],
    description: "A statement wool coat built to last through many winters.",
  },
  {
    name: "Ribbed Knit Top",
    category: "Women's Clothing",
    price: 1199,
    stock: 40,
    rating: 4.3,
    reviewCount: 720,
    keySpecs: ["Soft ribbed knit", "Flattering cut", "Long sleeve"],
    description: "A form-flattering knit top that works under cardigans or alone.",
  },
  {
    name: "Wide-Leg Trousers",
    category: "Women's Clothing",
    price: 2499,
    stock: 18,
    rating: 4.5,
    reviewCount: 389,
    keySpecs: ["High waist", "Crease line", "Tailored drape"],
    description: "Flowing wide-leg trousers with a clean crease down the front.",
  },
  {
    name: "Denim Jacket",
    category: "Women's Clothing",
    price: 3199,
    stock: 20,
    rating: 4.4,
    reviewCount: 512,
    keySpecs: ["Classic fit", "Stone-washed", "Metal buttons"],
    description: "The classic denim jacket in a worn-in stone-wash.",
  },
  {
    name: "Maxi Sundress",
    category: "Women's Clothing",
    price: 1899,
    stock: 33,
    rating: 4.6,
    reviewCount: 605,
    keySpecs: ["Breathable cotton", "Adjustable straps", "Floor length"],
    description: "A breezy floor-length sundress for warm afternoons.",
  },
  {
    name: "Cashmere Cardigan",
    category: "Women's Clothing",
    price: 5299,
    stock: 9,
    rating: 4.7,
    reviewCount: 220,
    keySpecs: ["Pure cashmere", "Button front", "Ribbed hem"],
    description: "An unbelievably soft button-up cardigan in pure cashmere.",
  },
];

// Out-of-stock products remain visible in search results (LLM sees inStock:
// false) and addToCart() refuses them while offering a real in-stock
// alternative from the same category.
export const OUT_OF_STOCK_NAMES: string[] = SEED_PRODUCTS.filter((p) => p.stock === 0).map((p) => p.name);