import type { Product } from "../types.js";

// 40 hackathon-sized products across the 4 allowed categories.
// A few carry stock:0 so the "offer an in-stock alternative" path is real
// and demonstrable. Do NOT add categories — the backend enforces the enum.
export type ProductSeed = Omit<Product, "id">;

const PRODUCT_SEED_DATA: ProductSeed[] = [
  // ---------------- Electronics ----------------
  {
    name: "Nova Wireless Earbuds",
    category: "Electronics",
    price: 2499,
    stock: 40,
    rating: 4.6,
    reviewCount: 1200,
    keySpecs: ["Bluetooth 5.3", "30h battery", "IPX5 splash-proof"],
    description: "Lightweight wireless earbuds with deep bass and a pocketable charging case.",
    appearance: {
      primaryColor: "pearl white",
      details: [
        "stem-style in-ear buds",
        "pebble-shaped charging case",
        "small LED status dot",
      ],
      texture: "smooth gloss finish",
      styleImpression: "minimal, understated",
      summary: "Pearl white earbuds with slim stems, sitting in a rounded pebble-shaped charging case with a smooth gloss finish.",
    },
  },
  {
    name: "Pulse Smart Watch Pro",
    category: "Electronics",
    price: 4299,
    stock: 25,
    rating: 4.4,
    reviewCount: 843,
    keySpecs: ["1.9 inch AMOLED", "7-day battery", "Built-in GPS"],
    description: "Fitness and notification smart watch with a bright always-on display.",
    appearance: {
      primaryColor: "graphite",
      secondaryColors: ["black"],
      details: [
        "rounded square watch face",
        "domed glass screen",
        "dark silicone band",
      ],
      texture: "brushed metal case with a glossy face",
      styleImpression: "technical, understated",
      summary: "A graphite rounded-square watch on a dark silicone band, with a brushed metal case and a slightly domed glass face.",
    },
  },
  {
    name: "Sona Bluetooth Speaker",
    category: "Electronics",
    price: 1999,
    stock: 60,
    rating: 4.3,
    reviewCount: 512,
    keySpecs: ["12W output", "10h playtime", "Waterproof"],
    description: "Portable speaker with punchy sound, made for indoor and outdoor use.",
    appearance: {
      primaryColor: "charcoal",
      details: [
        "cylindrical body",
        "recessed control strip along the top",
      ],
      texture: "matte woven fabric grille",
      styleImpression: "rugged, simple",
      summary: "A charcoal cylinder wrapped in a matte woven fabric grille, with a row of recessed controls along the top edge.",
    },
  },
  {
    name: "Volt 10000mAh Power Bank",
    category: "Electronics",
    price: 1499,
    stock: 80,
    rating: 4.5,
    reviewCount: 934,
    keySpecs: ["20W fast charge", "Dual USB-C", "Slim design"],
    description: "A slim power bank that tops up two devices at once.",
    appearance: {
      primaryColor: "black",
      details: [
        "thin rounded slab",
        "recessed port panel on one end",
        "small row of indicator dots",
      ],
      texture: "matte soft-touch",
      styleImpression: "plain, discreet",
      summary: "A thin matte black rounded slab with a recessed port panel on one end and a small row of indicator dots.",
    },
  },
  {
    name: "Vision 4K TV Stick",
    category: "Electronics",
    price: 3199,
    stock: 0,
    rating: 4.2,
    reviewCount: 388,
    keySpecs: ["4K HDR", "Voice remote", "32GB storage"],
    description: "Plug-in streaming stick that turns any screen into a smart TV.",
    appearance: {
      primaryColor: "black",
      details: [
        "small dongle form",
        "HDMI plug on one end",
        "short HDMI cable",
      ],
      texture: "matte plastic",
      styleImpression: "invisible, minimal",
      summary: "A small matte black dongle with an HDMI plug on one end and a short HDMI cable tucked alongside it.",
    },
  },
  {
    name: "Orbit Wireless Keyboard",
    category: "Electronics",
    price: 2799,
    stock: 20,
    rating: 4.4,
    reviewCount: 301,
    keySpecs: ["Backlit keys", "Low profile", "2.4GHz wireless"],
    description: "Quiet full-size keyboard with soft-touch keys and a battery that lasts months.",
    appearance: {
      primaryColor: "graphite grey",
      details: [
        "low-profile slab body",
        "flat chiclet keys",
        "thin bezel",
      ],
      texture: "soft matte keys",
      styleImpression: "clean, utilitarian",
      summary: "A low-profile graphite keyboard with a thin slab body, flat chiclet keys and a narrow bezel around the keys.",
    },
  },
  {
    name: "EchoMesh Wi-Fi Router",
    category: "Electronics",
    price: 2199,
    stock: 45,
    rating: 4.1,
    reviewCount: 210,
    keySpecs: ["AC1200", "5 antennas", "Parental controls"],
    description: "Dual-band router that blankets a small home in reliable Wi-Fi.",
    appearance: {
      primaryColor: "black",
      details: [
        "upright tower shape",
        "five slim antennas fanning from the back",
        "single front status light",
      ],
      texture: "matte plastic",
      styleImpression: "plain, functional",
      summary: "A matte black router standing as a plain upright tower, with five slim antennas fanning out from the back.",
    },
  },
  {
    name: "Aurora LED Desk Lamp",
    category: "Electronics",
    price: 1799,
    stock: 55,
    rating: 4.6,
    reviewCount: 676,
    keySpecs: ["3 color temperatures", "Touch dimmer", "USB charging port"],
    description: "An eye-friendly reading lamp with glare-free lighting for study or work.",
    appearance: {
      primaryColor: "white",
      secondaryColors: ["silver"],
      details: [
        "slim arched arm",
        "wide flat disc shade",
        "weighted round base",
      ],
      texture: "matte powder-coat",
      styleImpression: "clean, modern",
      summary: "A matte white desk lamp with a slim arched arm, a wide flat disc shade and a simple weighted round base.",
    },
  },
  {
    name: "SoundWave USB Microphone",
    category: "Electronics",
    price: 3499,
    stock: 18,
    rating: 4.7,
    reviewCount: 442,
    keySpecs: ["Podcast quality", "Plug and play", "Headphone monitoring"],
    description: "A plug-and-play mic that makes calls, meetings, and recordings crystal clear.",
    appearance: {
      primaryColor: "dark grey",
      details: [
        "cylindrical body",
        "round shock mount",
        "small gain dial",
      ],
      texture: "fine metal mesh grille",
      styleImpression: "studio, professional",
      summary: "A dark grey cylindrical microphone wrapped in a fine metal mesh grille, sitting in a matching round shock mount.",
    },
  },
  {
    name: "Nimbus Mini Projector",
    category: "Electronics",
    price: 8999,
    stock: 12,
    rating: 4.0,
    reviewCount: 168,
    keySpecs: ["HD 720p", "40-inch image", "Built-in speaker"],
    description: "A compact projector for cozy movie nights at home.",
    appearance: {
      primaryColor: "white",
      details: [
        "compact boxy body",
        "recessed glass lens on the front",
        "textured top panel",
      ],
      texture: "soft matte plastic",
      styleImpression: "compact, homey",
      summary: "A compact matte white projector with a recessed glass lens on the front and a finely textured top panel.",
    },
  },

  // ---------------- Jewelry ----------------
  {
    name: "Silver Crescent Necklace",
    category: "Jewelry",
    price: 2499,
    stock: 15,
    rating: 4.8,
    reviewCount: 521,
    keySpecs: ["925 sterling silver", "45cm chain", "Hypoallergenic"],
    description: "A delicate silver crescent pendant on a fine chain, safe for sensitive skin.",
    appearance: {
      primaryColor: "silver",
      details: [
        "crescent moon pendant",
        "very fine plain chain",
        "small bail at the top of the crescent",
      ],
      texture: "high-polish",
      styleImpression: "delicate, feminine",
      summary: "A polished silver crescent moon pendant hanging from a very fine, plain chain.",
    },
  },
  {
    name: "Pearl Drop Earrings",
    category: "Jewelry",
    price: 1799,
    stock: 30,
    rating: 4.5,
    reviewCount: 345,
    keySpecs: ["Cultured pearls", "Sterling silver posts", "Lightweight"],
    description: "Classic freshwater pearl drops that dress up anything.",
    appearance: {
      primaryColor: "ivory white",
      secondaryColors: ["silver"],
      details: [
        "teardrop-shaped pearls",
        "slim straight posts",
      ],
      texture: "smooth high-lustre",
      styleImpression: "classic, elegant",
      summary: "Creamy white teardrop pearls on slim silver posts, with a smooth, high-lustre surface.",
    },
  },
  {
    name: "Gold-Plated Bangle Set",
    category: "Jewelry",
    price: 3299,
    stock: 22,
    rating: 4.3,
    reviewCount: 278,
    keySpecs: ["3 bangles", "18k gold plated", "Tarnish resistant"],
    description: "A stack of three polished gold-plated bangles with a satisfying weight.",
    appearance: {
      primaryColor: "gold",
      details: [
        "three rounded bangles",
        "open-ended with a small gap",
      ],
      texture: "high-polish",
      styleImpression: "bold, warm",
      summary: "Three plain rounded bangles in warm polished gold, each open-ended with a small gap.",
    },
  },
  {
    name: "Onyx Bead Bracelet",
    category: "Jewelry",
    price: 999,
    stock: 40,
    rating: 4.6,
    reviewCount: 411,
    keySpecs: ["Natural onyx", "Stretch fit", "Unisex"],
    description: "A smooth matte-black bead bracelet you can slip on and forget.",
    appearance: {
      primaryColor: "black",
      details: [
        "strand of round beads of even size",
        "elastic band",
        "no clasp",
      ],
      texture: "smooth matte",
      styleImpression: "minimal, unisex",
      summary: "A strand of smooth, matte black round beads of even size, stretched onto a plain elastic band.",
    },
  },
  {
    name: "Sapphire Pendant Necklace",
    category: "Jewelry",
    price: 4499,
    stock: 10,
    rating: 4.7,
    reviewCount: 198,
    keySpecs: ["Lab sapphire", "18k plated chain", "Gift box included"],
    description: "A deep blue sapphire pendant on a long plated chain.",
    appearance: {
      primaryColor: "deep blue",
      secondaryColors: ["gold"],
      details: [
        "teardrop-cut stone",
        "slim gold setting",
        "long fine chain",
      ],
      texture: "faceted and bright",
      styleImpression: "regal, precious",
      summary: "A deep blue teardrop-cut stone in a slim gold setting, hung on a long fine gold chain.",
    },
  },
  {
    name: "Minimal Hoop Earrings",
    category: "Jewelry",
    price: 1199,
    stock: 50,
    rating: 4.4,
    reviewCount: 690,
    keySpecs: ["Feather light", "Tarnish-free finish", "Everyday wear"],
    description: "Round hoops so light you forget they are on.",
    appearance: {
      primaryColor: "silver",
      details: [
        "two thin matching hoops",
        "no charms or stones",
        "small hinge closure",
      ],
      texture: "high-polish",
      styleImpression: "minimalist, everyday",
      summary: "Two very thin, unadorned silver hoops of the same size, with a plain polished finish.",
    },
  },
  {
    name: "Rose Gold Ring Set",
    category: "Jewelry",
    price: 2899,
    stock: 14,
    rating: 4.5,
    reviewCount: 233,
    keySpecs: ["Stackable set", "Adjustable fit", "Rose gold tone"],
    description: "A set of three slim stackable rings in warm rose gold.",
    appearance: {
      primaryColor: "rose gold",
      details: [
        "three slim plain bands",
        "narrow enough to stack together",
      ],
      texture: "high-polish",
      styleImpression: "delicate, warm",
      summary: "Three slim, plain bands in warm rose gold, each narrow enough to stack together.",
    },
  },
  {
    name: "Turquoise Stud Earrings",
    category: "Jewelry",
    price: 1599,
    stock: 0,
    rating: 4.2,
    reviewCount: 154,
    keySpecs: ["Turquoise inlay", "Sterling posts", "Small and neat"],
    description: "Crisp turquoise studs set in a simple silver base.",
    appearance: {
      primaryColor: "turquoise blue",
      secondaryColors: ["silver"],
      details: [
        "small round cabochon studs",
        "plain silver base",
      ],
      texture: "smooth polished stone",
      styleImpression: "neat, understated",
      summary: "Small round turquoise-blue cabochon studs set on a plain silver base.",
    },
  },
  {
    name: "Twisted Knot Anklet",
    category: "Jewelry",
    price: 1349,
    stock: 32,
    rating: 4.3,
    reviewCount: 187,
    keySpecs: ["Sterling silver", "Adjustable chain", "42 inch length"],
    description: "A fine twisted-chain anklet with a simple knot detail.",
    appearance: {
      primaryColor: "silver",
      details: [
        "rope-twist chain",
        "small knot at the centre",
        "adjustable slider",
      ],
      texture: "twisted, reflective",
      styleImpression: "delicate, summery",
      summary: "A fine silver anklet with a rope-twist texture, gathered into a small knot at the centre.",
    },
  },
  {
    name: "Diamond-Cut Tennis Bracelet",
    category: "Jewelry",
    price: 5999,
    stock: 8,
    rating: 4.8,
    reviewCount: 302,
    keySpecs: ["Cubic zirconia", "Lobster clasp", "18k plated"],
    description: "A shimmering tennis bracelet that catches the light from every angle.",
    appearance: {
      primaryColor: "silver",
      secondaryColors: ["clear"],
      details: [
        "continuous line of round faceted stones",
        "link-set band",
        "lobster clasp",
      ],
      texture: "bright, highly reflective",
      styleImpression: "glamorous, formal",
      summary: "A continuous line of round, faceted clear stones set in a silver-toned link bracelet that catches the light from every angle.",
    },
  },

  // ---------------- Men's Clothing ----------------
  {
    name: "Classic Oxford Shirt",
    category: "Men's Clothing",
    price: 1499,
    stock: 40,
    rating: 4.4,
    reviewCount: 892,
    keySpecs: ["Soft cotton", "Wrinkle-free", "Regular fit"],
    description: "A wardrobe-staple oxford in a breathable, easy-care weave.",
    appearance: {
      primaryColor: "white",
      details: [
        "soft buttoned collar",
        "button front",
        "long sleeves",
        "regular straight body",
      ],
      texture: "smooth matte weave",
      styleImpression: "classic, crisp",
      summary: "A crisp white button-down shirt with a soft buttoned collar, long sleeves and a regular straight-cut body.",
    },
  },
  {
    name: "Slim Denim Jeans",
    category: "Men's Clothing",
    price: 2199,
    stock: 28,
    rating: 4.5,
    reviewCount: 1210,
    keySpecs: ["Stretch denim", "5-pocket style", "Slim leg"],
    description: "Everyday jeans with just enough stretch to stay comfortable all day.",
    appearance: {
      primaryColor: "dark blue indigo",
      details: [
        "five-pocket front",
        "slim close-cut leg",
        "faded whiskering at the thigh",
      ],
      texture: "soft washed denim",
      styleImpression: "casual, everyday",
      summary: "Dark blue indigo slim jeans with a faded, lightly whiskered front and a close-cut leg.",
    },
  },
  {
    name: "Merino Crew Sweater",
    category: "Men's Clothing",
    price: 2799,
    stock: 20,
    rating: 4.6,
    reviewCount: 655,
    keySpecs: ["100% merino wool", "Warm but light", "Machine washable"],
    description: "A fine-gauge merino sweater that layers easily under a coat.",
    appearance: {
      primaryColor: "charcoal grey",
      details: [
        "plain round crew neck",
        "close-fitting long sleeves",
        "fine rib at the cuffs and hem",
      ],
      texture: "fine smooth knit",
      styleImpression: "smart, minimal",
      summary: "A charcoal grey fine-gauge knit with a plain round crew neck and close-fitting long sleeves.",
    },
  },
  {
    name: "Everyday Chino Pants",
    category: "Men's Clothing",
    price: 1899,
    stock: 35,
    rating: 4.3,
    reviewCount: 540,
    keySpecs: ["Tapered cut", "4 colors", "Machine washable"],
    description: "Sharp chinos that go from office to evening without a fuss.",
    appearance: {
      primaryColor: "tan",
      details: [
        "flat front",
        "tapered leg",
        "slanted side pockets",
        "clean unwashed finish",
      ],
      texture: "smooth matte twill",
      styleImpression: "smart-casual",
      summary: "Warm tan chinos with a flat front, a tapered leg and a clean, unwashed finish.",
    },
  },
  {
    name: "Lightweight Bomber Jacket",
    category: "Men's Clothing",
    price: 3299,
    stock: 15,
    rating: 4.4,
    reviewCount: 372,
    keySpecs: ["Water resistant", "Breathable shell", "2 zip pockets"],
    description: "A packable bomber that shrugs off light rain and wind.",
    appearance: {
      primaryColor: "deep olive",
      details: [
        "full-length zip front",
        "ribbed cuffs and hem",
        "lightly padded body",
        "shirt collar",
      ],
      texture: "smooth matte shell",
      styleImpression: "casual, sporty",
      summary: "A deep olive bomber with a full zip front, ribbed cuffs and hem, and a lightly padded body.",
    },
  },
  {
    name: "Cotton Crew T-Shirt 3-Pack",
    category: "Men's Clothing",
    price: 1099,
    stock: 60,
    rating: 4.2,
    reviewCount: 1430,
    keySpecs: ["100% combed cotton", "Set of 3", "Pre-shrunk"],
    description: "Three soft, sturdy crew tees that hold their shape wash after wash.",
    appearance: {
      primaryColor: "white",
      secondaryColors: ["heather grey", "black"],
      details: [
        "plain round crew neck",
        "regular straight body",
        "short sleeves",
        "set of three colours",
      ],
      texture: "smooth soft jersey",
      styleImpression: "basic, everyday",
      summary: "Plain crew-neck tees in white, heather grey and black, each with a regular straight body and short sleeves.",
    },
  },
  {
    name: "Tailored Navy Blazer",
    category: "Men's Clothing",
    price: 5499,
    stock: 12,
    rating: 4.6,
    reviewCount: 210,
    keySpecs: ["Structured fit", "Horn buttons", "2-button closure"],
    description: "A sharp navy blazer that finishes a formal look.",
    appearance: {
      primaryColor: "deep navy blue",
      details: [
        "notched lapels",
        "two-button front",
        "lightly structured shoulder",
        "flap pockets",
      ],
      texture: "smooth matte suiting cloth",
      styleImpression: "sharp, formal",
      summary: "A deep navy blue single-breasted blazer with notched lapels, a two-button front and a lightly structured shoulder.",
    },
  },
  {
    name: "Fleece Hoodie",
    category: "Men's Clothing",
    price: 1799,
    stock: 45,
    rating: 4.3,
    reviewCount: 988,
    keySpecs: ["Brushed fleece", "Kangaroo pocket", "Drawstring hood"],
    description: "A heavyweight hoodie for cold mornings and lazy weekends.",
    appearance: {
      primaryColor: "mid grey",
      details: [
        "drawstring hood",
        "kangaroo pocket",
        "ribbed cuffs",
      ],
      texture: "brushed soft fleece",
      styleImpression: "casual, cosy",
      summary: "A mid grey heavyweight hoodie with a drawstring hood, a kangaroo pocket and ribbed cuffs.",
    },
  },
  {
    name: "Linen Summer Shirt",
    category: "Men's Clothing",
    price: 1599,
    stock: 0,
    rating: 4.1,
    reviewCount: 456,
    keySpecs: ["Pure linen", "Breathable", "Long sleeve"],
    description: "A light, airy linen shirt made for warm weather.",
    appearance: {
      primaryColor: "cream",
      details: [
        "soft open collar",
        "long sleeves",
        "relaxed untucked body",
        "straight hem",
      ],
      texture: "lightly crinkled woven linen",
      styleImpression: "relaxed, airy",
      summary: "A light cream linen shirt with a soft open collar, long sleeves and a relaxed, untucked body.",
    },
  },
  {
    name: "Jogger Sweatpants",
    category: "Men's Clothing",
    price: 1299,
    stock: 38,
    rating: 4.2,
    reviewCount: 610,
    keySpecs: ["Elastic waist", "Tapered leg", "Side pockets"],
    description: "Soft tapered joggers with a secure drawstring waist.",
    appearance: {
      primaryColor: "dark grey",
      details: [
        "elastic drawstring waist",
        "tapered leg",
        "side pockets",
        "ribbed ankle cuffs",
      ],
      texture: "brushed loopback fleece",
      styleImpression: "casual, sporty",
      summary: "Dark grey tapered sweatpants with an elastic drawstring waist, side pockets and ribbed ankle cuffs.",
    },
  },

  // ---------------- Women's Clothing ----------------
  {
    name: "Floral Wrap Dress",
    category: "Women's Clothing",
    price: 2499,
    stock: 25,
    rating: 4.7,
    reviewCount: 830,
    keySpecs: ["Flattering wrap", "Side pockets", "Knee length"],
    description: "A flowy wrap dress with a tie waist and handy pockets.",
    appearance: {
      primaryColor: "cream",
      secondaryColors: ["navy", "sage"],
      pattern: "small scattered floral sprigs",
      details: [
        "flutter short sleeves",
        "V-neck wrap bodice",
        "self-fabric tie waist",
        "knee-length skirt",
        "side seam pockets",
      ],
      texture: "light, softly draping woven fabric",
      styleImpression: "feminine, warm-weather",
      summary: "A cream wrap dress scattered with small navy and sage floral sprigs, with flutter short sleeves, a V-neck wrap bodice, a self-tie waist and a knee-length skirt.",
    },
  },
  {
    name: "High-Rise Leggings",
    category: "Women's Clothing",
    price: 1399,
    stock: 50,
    rating: 4.5,
    reviewCount: 1560,
    keySpecs: ["Squat-proof", "4-way stretch", "High waist"],
    description: "Seamless-feel leggings that stay put through any workout.",
    appearance: {
      primaryColor: "black",
      details: [
        "wide high-rise waistband",
        "ankle-length legs",
        "no visible seams",
      ],
      texture: "smooth matte stretch knit",
      styleImpression: "minimal, sleek",
      summary: "Matte black ankle-length leggings with a wide high-rise waistband and no visible seams.",
    },
  },
  {
    name: "Silk Blouse",
    category: "Women's Clothing",
    price: 2099,
    stock: 22,
    rating: 4.6,
    reviewCount: 410,
    keySpecs: ["100% mulberry silk", "Pearl buttons", "Dry clean"],
    description: "A luxuriously smooth silk blouse with delicate pearl buttons.",
    appearance: {
      primaryColor: "ivory",
      details: [
        "softly rounded neckline",
        "small pearl buttons down the front",
        "relaxed drape",
        "long sleeves",
      ],
      texture: "fluid, softly lustrous",
      styleImpression: "elegant, understated",
      summary: "A soft ivory silk blouse with a relaxed drape, a softly rounded neckline and small pearl buttons down the front.",
    },
  },
  {
    name: "A-Line Floral Skirt",
    category: "Women's Clothing",
    price: 1799,
    stock: 26,
    rating: 4.4,
    reviewCount: 355,
    keySpecs: ["Midi length", "Hidden zip", "Lined"],
    description: "A twirlable midi skirt in a soft floral print.",
    appearance: {
      primaryColor: "cream",
      secondaryColors: ["coral", "sage"],
      pattern: "small scattered floral",
      details: [
        "A-line silhouette",
        "neat fitted waistband",
        "mid-calf length",
        "fully lined",
      ],
      texture: "light, softly draping woven fabric",
      styleImpression: "feminine, summery",
      summary: "A small-floral A-line skirt in cream with coral and sage sprigs, sitting mid-calf with a neat fitted waistband.",
    },
  },
  {
    name: "Wool Tailored Coat",
    category: "Women's Clothing",
    price: 6999,
    stock: 10,
    rating: 4.8,
    reviewCount: 264,
    keySpecs: ["Structured wool", "Double breasted", "Long length"],
    description: "A statement wool coat built to last through many winters.",
    appearance: {
      primaryColor: "camel",
      details: [
        "wide notched lapels",
        "double-breasted front",
        "below-knee hem",
        "wide sleeves",
      ],
      texture: "dense, brushed wool",
      styleImpression: "statement, tailored",
      summary: "A camel wool coat with wide notched lapels, a double-breasted front and a long hem that falls below the knee.",
    },
  },
  {
    name: "Ribbed Knit Top",
    category: "Women's Clothing",
    price: 1199,
    stock: 40,
    rating: 4.3,
    reviewCount: 720,
    keySpecs: ["Soft ribbed knit", "Flattering cut", "Long sleeve"],
    description: "A form-flattering knit top that works under cardigans or alone.",
    appearance: {
      primaryColor: "cream",
      details: [
        "body-skimming shape",
        "long sleeves",
        "simple round neck",
        "ribbed throughout",
      ],
      texture: "soft vertical rib knit",
      styleImpression: "fitted, minimal",
      summary: "A cream ribbed knit top with a close, body-skimming shape, long sleeves and a simple round neck.",
    },
  },
  {
    name: "Wide-Leg Trousers",
    category: "Women's Clothing",
    price: 2499,
    stock: 18,
    rating: 4.5,
    reviewCount: 389,
    keySpecs: ["High waist", "Crease line", "Tailored drape"],
    description: "Flowing wide-leg trousers with a clean crease down the front.",
    appearance: {
      primaryColor: "charcoal",
      details: [
        "high waist",
        "wide fluid leg",
        "sharp pressed crease down the front",
        "front pleats",
      ],
      texture: "smooth matte suiting cloth",
      styleImpression: "tailored, elegant",
      summary: "Charcoal high-waisted trousers with a wide, fluid leg and a sharp pressed crease down the front.",
    },
  },
  {
    name: "Denim Jacket",
    category: "Women's Clothing",
    price: 3199,
    stock: 20,
    rating: 4.4,
    reviewCount: 512,
    keySpecs: ["Classic fit", "Stone-washed", "Metal buttons"],
    description: "The classic denim jacket in a worn-in stone-wash.",
    appearance: {
      primaryColor: "light blue",
      details: [
        "pointed collar",
        "button front",
        "cropped boxy body",
        "two flap chest pockets",
      ],
      texture: "soft stone-washed denim",
      styleImpression: "casual, vintage",
      summary: "A light stone-washed blue denim trucker jacket with a pointed collar, a button front and a cropped, boxy body.",
    },
  },
  {
    name: "Maxi Sundress",
    category: "Women's Clothing",
    price: 1899,
    stock: 33,
    rating: 4.6,
    reviewCount: 605,
    keySpecs: ["Breathable cotton", "Adjustable straps", "Floor length"],
    description: "A breezy floor-length sundress for warm afternoons.",
    appearance: {
      primaryColor: "sand",
      pattern: "fine vertical stripes",
      details: [
        "slim adjustable straps",
        "deep neckline",
        "flowing floor-length skirt",
        "side seam pockets",
      ],
      texture: "light, softly draping woven fabric",
      styleImpression: "relaxed, summery",
      summary: "A sand-coloured maxi sundress with fine vertical stripes, slim adjustable straps and a deep neckline.",
    },
  },
  {
    name: "Cashmere Cardigan",
    category: "Women's Clothing",
    price: 5299,
    stock: 9,
    rating: 4.7,
    reviewCount: 220,
    keySpecs: ["Pure cashmere", "Button front", "Ribbed hem"],
    description: "An unbelievably soft button-up cardigan in pure cashmere.",
    appearance: {
      primaryColor: "oatmeal",
      details: [
        "button front",
        "ribbed cuffs and hem",
        "soft shawl collar",
        "relaxed body",
      ],
      texture: "plush, brushed cashmere",
      styleImpression: "cosy, understated",
      summary: "A soft oatmeal cashmere cardigan with a simple button front, a soft shawl collar and ribbed cuffs and hem.",
    },
  },

  // ---------------- Electronics (additional) ----------------
  {
    name: "SnapPad Wireless Charger",
    category: "Electronics",
    price: 1399,
    stock: 35,
    rating: 4.3,
    reviewCount: 482,
    keySpecs: ["15W fast wireless", "Universal Qi", "LED indicator"],
    description: "A slim wireless pad that charges most smartphones fast.",
    appearance: {
      primaryColor: "white",
      details: ["thin round disc", "single centre LED dot", "anti-slip base"],
      texture: "soft matte surface",
      styleImpression: "clean, unobtrusive",
      summary: "A thin white round charging disc with a single centre LED indicator and a soft matte surface.",
    },
  },
  {
    name: "FocusCam 1080p Webcam",
    category: "Electronics",
    price: 2899,
    stock: 22,
    rating: 4.5,
    reviewCount: 317,
    keySpecs: ["1080p / 30fps", "Built-in stereo mic", "Clip mount"],
    description: "Crystal-clear video for calls, streams, and recordings.",
    appearance: {
      primaryColor: "black",
      details: ["wide barrel lens housing", "adjustable clip on base", "status LED ring"],
      texture: "matte plastic",
      styleImpression: "minimal, professional",
      summary: "A matte black barrel-shaped webcam with a wide lens and an adjustable clip base.",
    },
  },
  {
    name: "Chill Mini Fan",
    category: "Electronics",
    price: 799,
    stock: 50,
    rating: 4.1,
    reviewCount: 620,
    keySpecs: ["USB powered", "3-speed", "360° tilt"],
    description: "A quiet USB desk fan for warm days in the office or at home.",
    appearance: {
      primaryColor: "white",
      secondaryColors: ["light grey"],
      details: ["round blade guard", "small stable base", "smooth tilt joint"],
      texture: "smooth plastic",
      styleImpression: "simple, cute",
      summary: "A small white round desktop fan with a smooth blade guard and a simple tilting base.",
    },
  },

  // ---------------- Jewelry (additional) ----------------
  {
    name: "Layered Chain Necklace",
    category: "Jewelry",
    price: 1899,
    stock: 28,
    rating: 4.4,
    reviewCount: 390,
    keySpecs: ["3-layer design", "Tarnish-resistant", "Adjustable length"],
    description: "Three delicate chains of different lengths that wear as one layered piece.",
    appearance: {
      primaryColor: "gold",
      details: ["three chains of stepped lengths", "no pendants", "shared lobster clasp"],
      texture: "polished smooth links",
      styleImpression: "effortless, modern",
      summary: "Three fine gold chains of different lengths worn together, sharing a single clasp for an effortless layered look.",
    },
  },
  {
    name: "Geometric Ear Cuffs",
    category: "Jewelry",
    price: 1099,
    stock: 35,
    rating: 4.3,
    reviewCount: 212,
    keySpecs: ["No piercing needed", "Adjustable grip", "Set of 2"],
    description: "Angular ear cuffs that wrap the cartilage without a piercing.",
    appearance: {
      primaryColor: "silver",
      details: ["open angular shape", "smooth inner grip", "architectural flat band"],
      texture: "polished metal",
      styleImpression: "architectural, edgy",
      summary: "Polished silver open-angular ear cuffs with a smooth grip, worn without piercing.",
    },
  },
  {
    name: "Birthstone Pendant Set",
    category: "Jewelry",
    price: 2199,
    stock: 20,
    rating: 4.6,
    reviewCount: 275,
    keySpecs: ["12 stone options", "Sterling silver chain", "Gift box"],
    description: "A dainty round pendant set with your chosen birthstone.",
    appearance: {
      primaryColor: "silver",
      secondaryColors: ["light blue"],
      details: ["small round bezel-set stone", "fine cable chain", "four-prong setting"],
      texture: "polished silver with faceted stone",
      styleImpression: "personal, delicate",
      summary: "A small round birthstone in a polished silver bezel setting on a fine cable chain.",
    },
  },

  // ---------------- Men's Clothing (additional) ----------------
  {
    name: "Slim Fit Formal Shirt",
    category: "Men's Clothing",
    price: 1699,
    stock: 32,
    rating: 4.5,
    reviewCount: 735,
    keySpecs: ["Cotton blend", "Slim fit", "Non-iron finish"],
    description: "A tailored slim shirt with a smooth, wrinkle-resistant finish.",
    appearance: {
      primaryColor: "sky blue",
      details: ["pointed collar", "slim cut through the body", "single-button cuffs"],
      texture: "smooth fine poplin",
      styleImpression: "crisp, office-ready",
      summary: "A crisp sky blue slim-fit shirt with a pointed collar and single-button cuffs.",
    },
  },
  {
    name: "Cargo Shorts",
    category: "Men's Clothing",
    price: 1199,
    stock: 42,
    rating: 4.2,
    reviewCount: 890,
    keySpecs: ["6 pockets", "Knee length", "Ripstop fabric"],
    description: "Durable knee-length cargo shorts with six functional pockets.",
    appearance: {
      primaryColor: "khaki",
      details: ["four main pockets", "two thigh patch pockets with velcro flaps", "drawstring hem"],
      texture: "tough ripstop weave",
      styleImpression: "utilitarian, casual",
      summary: "Khaki knee-length cargo shorts with two large thigh pockets and a sturdy ripstop weave.",
    },
  },
  {
    name: "Quilted Puffer Vest",
    category: "Men's Clothing",
    price: 2299,
    stock: 18,
    rating: 4.4,
    reviewCount: 298,
    keySpecs: ["Light insulation", "Zip pockets", "Packable"],
    description: "A lightweight vest that adds warmth without bulk.",
    appearance: {
      primaryColor: "navy",
      details: ["horizontal channel quilting", "zip chest pocket", "ribbed hem"],
      texture: "smooth nylon shell, light fill",
      styleImpression: "sporty, layered",
      summary: "A navy quilted vest with horizontal channel stitching, a zip chest pocket and a ribbed hem.",
    },
  },
  {
    name: "Printed Graphic Tee",
    category: "Men's Clothing",
    price: 799,
    stock: 60,
    rating: 4.1,
    reviewCount: 1100,
    keySpecs: ["Cotton jersey", "Crew neck", "Relaxed fit"],
    description: "A relaxed-fit tee with a bold abstract chest graphic.",
    appearance: {
      primaryColor: "black",
      secondaryColors: ["white"],
      details: ["oversized abstract print on chest", "plain crew neck", "dropped shoulders"],
      texture: "soft cotton jersey",
      styleImpression: "streetwear, bold",
      summary: "A black relaxed-fit tee with a bold white abstract graphic across the chest and dropped shoulders.",
    },
  },

  // ---------------- Women's Clothing (additional) ----------------
  {
    name: "Linen Palazzo Pants",
    category: "Women's Clothing",
    price: 1999,
    stock: 30,
    rating: 4.5,
    reviewCount: 418,
    keySpecs: ["Flowy linen", "Elasticated waist", "Floor grazing"],
    description: "Wide palazzo trousers in a breezy linen that flows when you walk.",
    appearance: {
      primaryColor: "cream",
      details: ["very wide floor-length leg", "elasticated waist", "draped side silhouette"],
      texture: "lightly woven linen",
      styleImpression: "resort, relaxed",
      summary: "Cream linen palazzo trousers with a very wide floor-length leg and a soft elasticated waist.",
    },
  },
  {
    name: "Crop Puff-Sleeve Top",
    category: "Women's Clothing",
    price: 1299,
    stock: 25,
    rating: 4.4,
    reviewCount: 560,
    keySpecs: ["Cotton blend", "Puff sleeves", "Cropped length"],
    description: "A sweet cropped blouse with exaggerated puff sleeves.",
    appearance: {
      primaryColor: "blush pink",
      details: ["gathered balloon sleeves", "square neckline", "cropped at the waist"],
      texture: "light woven cotton",
      styleImpression: "romantic, playful",
      summary: "A blush pink cropped top with a square neckline and exaggerated balloon sleeves.",
    },
  },
  {
    name: "Bodycon Midi Dress",
    category: "Women's Clothing",
    price: 2299,
    stock: 20,
    rating: 4.6,
    reviewCount: 345,
    keySpecs: ["Stretch jersey", "Midi length", "Round neck"],
    description: "A form-fitting midi in smooth stretch jersey.",
    appearance: {
      primaryColor: "forest green",
      details: ["round neck", "short sleeves", "fitted through the body", "midi hem"],
      texture: "smooth matte stretch jersey",
      styleImpression: "sleek, polished",
      summary: "A forest green form-fitting midi dress with a round neck, short sleeves and a smooth matte finish.",
    },
  },
  {
    name: "Oversized Hoodie Dress",
    category: "Women's Clothing",
    price: 1799,
    stock: 28,
    rating: 4.3,
    reviewCount: 487,
    keySpecs: ["Fleece lined", "Mini length", "Kangaroo pocket"],
    description: "A cosy oversized hoodie that doubles as a mini dress.",
    appearance: {
      primaryColor: "charcoal",
      details: ["drawstring hood", "kangaroo pocket", "dropped shoulders", "mini skirt length"],
      texture: "soft brushed fleece",
      styleImpression: "cosy, streetwear",
      summary: "A charcoal oversized hoodie dress with a drawstring hood, kangaroo pocket and dropped shoulders.",
    },
  },

  // ──────────────────────── ELECTRONICS (more) ────────────────────────

  {
    name: "NightOwl Smart LED Bulb",
    category: "Electronics",
    price: 899,
    stock: 70,
    rating: 4.3,
    reviewCount: 841,
    keySpecs: ["16M colours", "Voice control", "E27 base"],
    description: "A Wi-Fi smart bulb that fits any standard socket and pairs with Alexa or Google.",
    appearance: {
      primaryColor: "white",
      details: ["standard bulb shape", "frosted glass dome", "no visible LED strips"],
      texture: "smooth frosted glass",
      styleImpression: "invisible, smart-home",
      summary: "A standard frosted white bulb that looks ordinary until you turn it on in any colour.",
    },
  },
  {
    name: "DeskPro Standing Mat",
    category: "Electronics",
    price: 2199,
    stock: 30,
    rating: 4.6,
    reviewCount: 390,
    keySpecs: ["Anti-fatigue foam", "Non-slip base", "75×50 cm"],
    description: "An ergonomic standing mat with deep cushioning for long desk sessions.",
    appearance: {
      primaryColor: "dark charcoal",
      details: ["thick rectangular pad", "slight raised edges", "textured top surface"],
      texture: "firm anti-fatigue foam with rubberised base",
      styleImpression: "functional, minimal",
      summary: "A thick dark charcoal anti-fatigue mat with a textured surface and slightly raised edges.",
    },
  },
  {
    name: "GlideX Gaming Mouse",
    category: "Electronics",
    price: 1899,
    stock: 25,
    rating: 4.5,
    reviewCount: 624,
    keySpecs: ["12000 DPI", "6 buttons", "RGB lighting"],
    description: "A precise wired gaming mouse with smooth glide and colour-customisable lighting.",
    appearance: {
      primaryColor: "black",
      secondaryColors: ["RGB"],
      details: ["ergonomic right-hand grip", "two side buttons", "glowing scroll wheel and logo"],
      texture: "matte textured sides, smooth top",
      styleImpression: "gaming, aggressive",
      summary: "A matte black ergonomic gaming mouse with RGB-lit scroll wheel and side logo.",
    },
  },
  {
    name: "PocketScan Portable Scanner",
    category: "Electronics",
    price: 3799,
    stock: 14,
    rating: 4.2,
    reviewCount: 175,
    keySpecs: ["A4 documents", "600 DPI", "USB + Wi-Fi"],
    description: "A slim portable scanner that digitises documents directly to your phone.",
    appearance: {
      primaryColor: "white",
      details: ["flat slab shape", "narrow paper slot along the length", "small side button"],
      texture: "smooth matte plastic",
      styleImpression: "compact, office",
      summary: "A slim matte white slab with a narrow paper feed slot running its full length.",
    },
  },
  {
    name: "SleepWave Alarm Clock",
    category: "Electronics",
    price: 1599,
    stock: 40,
    rating: 4.4,
    reviewCount: 508,
    keySpecs: ["Sunrise simulation", "FM radio", "USB charge port"],
    description: "A sunrise alarm clock that wakes you gently with light and soft sound.",
    appearance: {
      primaryColor: "cream white",
      details: ["smooth round disc face", "amber glow ring on the base", "minimal top controls"],
      texture: "soft matte plastic",
      styleImpression: "calm, wellness",
      summary: "A smooth round cream-coloured alarm clock with a warm amber glow ring around the base.",
    },
  },

  // ──────────────────────── JEWELRY (more) ────────────────────────

  {
    name: "Hammered Coin Pendant",
    category: "Jewelry",
    price: 1799,
    stock: 22,
    rating: 4.5,
    reviewCount: 260,
    keySpecs: ["Gold-plated", "45cm chain", "Handcrafted finish"],
    description: "A textured coin pendant with a hammered finish on a delicate chain.",
    appearance: {
      primaryColor: "gold",
      details: ["flat round disc pendant", "irregular hammered dimples", "short bail at top"],
      texture: "hammered matte gold finish",
      styleImpression: "artisan, bohemian",
      summary: "A gold flat coin pendant with a handcrafted hammered texture, hanging on a fine gold chain.",
    },
  },
  {
    name: "Crystal Drop Choker",
    category: "Jewelry",
    price: 2299,
    stock: 18,
    rating: 4.6,
    reviewCount: 195,
    keySpecs: ["Crystal drops", "Adjustable length", "Silver-tone"],
    description: "A silver choker with three delicate crystal drops of varied lengths.",
    appearance: {
      primaryColor: "silver",
      secondaryColors: ["clear crystal"],
      details: ["close-fitting chain", "three teardrop crystal pendants at the front", "lobster clasp"],
      texture: "polished chain, faceted crystals",
      styleImpression: "glamorous, statement",
      summary: "A close-fitting silver chain choker with three clear teardrop crystals hanging at different lengths.",
    },
  },
  {
    name: "Black Onyx Stud Set",
    category: "Jewelry",
    price: 1499,
    stock: 30,
    rating: 4.4,
    reviewCount: 330,
    keySpecs: ["Set of 3 pairs", "Sterling silver posts", "Everyday wear"],
    description: "Three pairs of round onyx studs in graduated sizes — mix and stack them.",
    appearance: {
      primaryColor: "black",
      secondaryColors: ["silver"],
      details: ["three pairs of round matte-black cabochons", "plain silver post and butterfly back"],
      texture: "smooth matte stone, polished silver mount",
      styleImpression: "minimal, modern",
      summary: "Three pairs of graduated round black onyx studs on plain silver posts, from small to medium.",
    },
  },
  {
    name: "Enamel Floral Bangle",
    category: "Jewelry",
    price: 1999,
    stock: 20,
    rating: 4.3,
    reviewCount: 148,
    keySpecs: ["Enamel painted", "Brass base", "One size fits most"],
    description: "A wide bangle painted with tiny pastel floral details on an ivory background.",
    appearance: {
      primaryColor: "ivory",
      secondaryColors: ["blush", "sage", "gold"],
      pattern: "tiny hand-painted floral motifs",
      details: ["wide band", "flat smooth surface with painted design", "gold-tone rim"],
      texture: "smooth enamel surface",
      styleImpression: "feminine, artisan",
      summary: "A wide ivory enamel bangle with tiny pastel floral motifs painted across the surface and a gold-tone rim.",
    },
  },
  {
    name: "Bold Chunky Chain Necklace",
    category: "Jewelry",
    price: 2699,
    stock: 16,
    rating: 4.5,
    reviewCount: 278,
    keySpecs: ["Chunky links", "Gold-plated", "45cm length"],
    description: "A statement chunky chain in gold-tone that dresses up any outfit.",
    appearance: {
      primaryColor: "gold",
      details: ["large oval links", "no pendant", "lobster clasp"],
      texture: "high-polish gold plating",
      styleImpression: "statement, bold",
      summary: "A bold gold-tone chunky chain necklace with large oval links and a high-polish finish.",
    },
  },

  // ──────────────────────── MEN'S CLOTHING (more) ────────────────────────

  {
    name: "Slim Shorts",
    category: "Men's Clothing",
    price: 999,
    stock: 50,
    rating: 4.2,
    reviewCount: 740,
    keySpecs: ["7-inch inseam", "Stretch fabric", "Two pockets"],
    description: "Slim-fit chino shorts that go from the gym to the street.",
    appearance: {
      primaryColor: "navy",
      details: ["above-knee length", "clean flat front", "two side pockets"],
      texture: "smooth stretch twill",
      styleImpression: "clean, minimal",
      summary: "Slim-cut navy shorts with a flat front, clean lines and a subtle stretch.",
    },
  },
  {
    name: "Striped Rugby Shirt",
    category: "Men's Clothing",
    price: 1899,
    stock: 28,
    rating: 4.4,
    reviewCount: 415,
    keySpecs: ["Pique cotton", "Buttoned collar", "Long sleeves"],
    description: "A classic rugby shirt in a bold two-tone horizontal stripe.",
    appearance: {
      primaryColor: "navy",
      secondaryColors: ["white"],
      pattern: "horizontal broad stripes",
      details: ["thick horizontal stripes alternating navy and white", "small buttoned collar", "long sleeves"],
      texture: "firm pique weave",
      styleImpression: "preppy, sporty",
      summary: "A bold navy and white horizontal-striped rugby shirt with a small buttoned collar.",
    },
  },
  {
    name: "Wool Flat Cap",
    category: "Men's Clothing",
    price: 1299,
    stock: 35,
    rating: 4.5,
    reviewCount: 520,
    keySpecs: ["Wool blend", "Adjustable strap", "Classic fit"],
    description: "A sharp wool flat cap in a traditional herringbone weave.",
    appearance: {
      primaryColor: "charcoal grey",
      pattern: "fine herringbone weave",
      details: ["low crown", "short stiff brim", "inner adjustable band"],
      texture: "warm textured wool blend",
      styleImpression: "classic, British",
      summary: "A charcoal grey flat cap woven in a fine herringbone pattern with a short stiff brim.",
    },
  },
  {
    name: "Pique Polo Shirt",
    category: "Men's Clothing",
    price: 1499,
    stock: 40,
    rating: 4.3,
    reviewCount: 965,
    keySpecs: ["100% cotton pique", "Three-button collar", "Regular fit"],
    description: "A clean polo shirt in breathable pique cotton — office casual done right.",
    appearance: {
      primaryColor: "white",
      details: ["ribbed polo collar", "two-button placket", "short sleeves", "straight hem"],
      texture: "pique knit",
      styleImpression: "clean, smart-casual",
      summary: "A crisp white pique polo shirt with a ribbed collar, short sleeves and a straight hem.",
    },
  },
  {
    name: "Reversible Padded Jacket",
    category: "Men's Clothing",
    price: 3999,
    stock: 12,
    rating: 4.6,
    reviewCount: 188,
    keySpecs: ["Reversible", "Puffer insulation", "2 zip pockets each side"],
    description: "Two jackets in one: a bold check pattern flips to reveal a plain black back.",
    appearance: {
      primaryColor: "black",
      secondaryColors: ["tan", "brown"],
      pattern: "reversible — plain black one side, plaid check the other",
      details: ["boxy puffer silhouette", "stand collar", "two zip pockets on each side"],
      texture: "smooth nylon shell, light puffer fill",
      styleImpression: "versatile, modern",
      summary: "A reversible puffer jacket — plain matte black on one side, tan-and-brown plaid check on the other.",
    },
  },

  // ──────────────────────── WOMEN'S CLOTHING (more) ────────────────────────

  {
    name: "Tie-Front Cami Top",
    category: "Women's Clothing",
    price: 1099,
    stock: 38,
    rating: 4.4,
    reviewCount: 610,
    keySpecs: ["Satin finish", "Adjustable tie", "Fitted cut"],
    description: "A slim satin cami with a tie knot at the front hem.",
    appearance: {
      primaryColor: "dusty rose",
      details: ["thin spaghetti straps", "wrap-style front with self-tie knot", "straight neckline"],
      texture: "fluid satin-finish fabric",
      styleImpression: "feminine, evening",
      summary: "A dusty rose satin cami with thin straps, a tie knot at the front and a smooth fluid drape.",
    },
  },
  {
    name: "Belted Trench Coat",
    category: "Women's Clothing",
    price: 5999,
    stock: 9,
    rating: 4.7,
    reviewCount: 305,
    keySpecs: ["Water resistant", "Self-belt", "Knee length"],
    description: "A classic knee-length trench coat in a smooth water-resistant shell.",
    appearance: {
      primaryColor: "camel",
      details: ["notched lapel", "double-breasted button front", "self-belt at waist", "epaulettes"],
      texture: "smooth water-resistant cotton blend",
      styleImpression: "timeless, Parisian",
      summary: "A camel classic trench coat with a double-breasted front, epaulettes and a self-belt at the waist.",
    },
  },
  {
    name: "High-Neck Knit Vest",
    category: "Women's Clothing",
    price: 1599,
    stock: 28,
    rating: 4.3,
    reviewCount: 342,
    keySpecs: ["Sleeveless", "Ribbed knit", "High neck"],
    description: "A sleeveless ribbed vest with a high neck — great layered over a shirt.",
    appearance: {
      primaryColor: "oatmeal",
      details: ["high mock neck", "sleeveless", "fitted ribbed body"],
      texture: "soft vertical rib knit",
      styleImpression: "minimal, contemporary",
      summary: "An oatmeal sleeveless ribbed vest with a high mock neck and a close-fitting silhouette.",
    },
  },
  {
    name: "Lace Hem Mini Skirt",
    category: "Women's Clothing",
    price: 1899,
    stock: 22,
    rating: 4.5,
    reviewCount: 278,
    keySpecs: ["Satin base", "Lace trim hem", "Side zip"],
    description: "A short satin skirt with delicate lace along the hem.",
    appearance: {
      primaryColor: "black",
      secondaryColors: ["ivory"],
      details: ["sleek A-line silhouette", "narrow lace trim at the hem", "hidden side zip"],
      texture: "smooth satin with lace border",
      styleImpression: "edgy, feminine",
      summary: "A black satin mini skirt with a delicate ivory lace trim at the hem.",
    },
  },
  {
    name: "Smocked Midi Dress",
    category: "Women's Clothing",
    price: 2199,
    stock: 25,
    rating: 4.6,
    reviewCount: 445,
    keySpecs: ["Elasticated smocking", "Tiered skirt", "Midi length"],
    description: "A boho-style midi dress with a smocked bodice and tiered flowing skirt.",
    appearance: {
      primaryColor: "terracotta",
      pattern: "small ditsy floral",
      details: ["smocked elasticated bodice", "square neckline", "three-tiered skirt", "short ruffled sleeves"],
      texture: "soft woven cotton",
      styleImpression: "bohemian, summery",
      summary: "A terracotta floral midi dress with a smocked square-neck bodice and a three-tiered flowing skirt.",
    },
  },
  {
    name: "Faux Leather Biker Jacket",
    category: "Women's Clothing",
    price: 4499,
    stock: 10,
    rating: 4.5,
    reviewCount: 360,
    keySpecs: ["Faux leather", "Silver hardware", "Moto-style"],
    description: "A moto-style faux leather jacket with exposed zip detailing.",
    appearance: {
      primaryColor: "black",
      details: ["asymmetric zip front", "zip cuffs", "small lapel collar", "three pockets with zip pulls"],
      texture: "smooth matte faux leather",
      styleImpression: "edgy, moto",
      summary: "A matte black faux leather biker jacket with an asymmetric zip front and zip-pull pockets.",
    },
  },

  // ──────────────────────── ELECTRONICS (batch 3) ────────────────────────

  {
    name: "StreamDeck Macro Pad",
    category: "Electronics",
    price: 4999,
    stock: 15,
    rating: 4.7,
    reviewCount: 913,
    keySpecs: ["15 LCD keys", "USB-C", "Customisable"],
    description: "A 15-key LCD macro pad that launches apps, macros and scenes with one tap.",
    appearance: {
      primaryColor: "black",
      details: ["compact 3×5 grid of square keys", "each key has a tiny colour display", "USB cable at the back"],
      texture: "matte plastic, smooth key surfaces",
      styleImpression: "tech, productive",
      summary: "A compact black macro pad with 15 small square LCD keys in a 3×5 grid.",
    },
  },
  {
    name: "ThermoMug Smart Travel Cup",
    category: "Electronics",
    price: 2499,
    stock: 32,
    rating: 4.4,
    reviewCount: 677,
    keySpecs: ["App-controlled temperature", "12hr hot", "Stainless steel"],
    description: "A smart travel mug that lets you set the exact temperature from your phone.",
    appearance: {
      primaryColor: "slate grey",
      details: ["smooth cylinder body", "flat lid with centre button", "minimal branding on the band"],
      texture: "brushed stainless steel",
      styleImpression: "premium, minimal",
      summary: "A brushed slate grey stainless steel travel mug with a flat snap lid and a small control button.",
    },
  },
  {
    name: "ProPen 2 Stylus",
    category: "Electronics",
    price: 1899,
    stock: 20,
    rating: 4.6,
    reviewCount: 420,
    keySpecs: ["8192 pressure levels", "Tilt support", "No battery"],
    description: "A battery-free precision stylus with near-zero lag for drawing tablets.",
    appearance: {
      primaryColor: "dark grey",
      details: ["slender pen shape", "flat clip on one side", "two side buttons near the tip", "no charging port"],
      texture: "matte rubberised barrel",
      styleImpression: "professional, precise",
      summary: "A slim dark grey stylus with a matte grip, two side buttons and a flat clip along the barrel.",
    },
  },
  {
    name: "LED Bias Lighting Strip",
    category: "Electronics",
    price: 1299,
    stock: 55,
    rating: 4.3,
    reviewCount: 1120,
    keySpecs: ["2m length", "USB-powered", "App-controlled RGBW"],
    description: "A 2m USB LED strip for monitor backlighting — dramatically reduces eye strain.",
    appearance: {
      primaryColor: "white",
      details: ["flat flexible strip", "adhesive backing", "USB connector at one end", "tiny LED dots every 2cm"],
      texture: "flexible silicone strip",
      styleImpression: "ambient, tech",
      summary: "A thin flexible white LED strip with adhesive backing and a USB connector, emitting RGBW ambient light.",
    },
  },
  {
    name: "BoltBase Fast Charger",
    category: "Electronics",
    price: 1099,
    stock: 60,
    rating: 4.5,
    reviewCount: 2340,
    keySpecs: ["65W GaN", "3 ports", "Foldable plug"],
    description: "A 65W GaN charger with two USB-C and one USB-A port in a palm-sized brick.",
    appearance: {
      primaryColor: "white",
      details: ["compact cube shape", "three ports on the front face", "fold-flat prongs"],
      texture: "smooth matte plastic",
      styleImpression: "compact, functional",
      summary: "A compact white cube charger with three front-facing ports and fold-flat prongs.",
    },
  },

  // ──────────────────────── JEWELRY (batch 3) ────────────────────────

  {
    name: "Pearl Cluster Ring",
    category: "Jewelry",
    price: 3199,
    stock: 12,
    rating: 4.6,
    reviewCount: 142,
    keySpecs: ["Freshwater pearls", "Gold-plated band", "Adjustable"],
    description: "A gold-plated ring with a small cluster of freshwater pearls at the centre.",
    appearance: {
      primaryColor: "gold",
      secondaryColors: ["cream white"],
      details: ["three small pearls grouped at the top", "thin polished band", "adjustable open back"],
      texture: "polished gold band, smooth pearl surface",
      styleImpression: "elegant, feminine",
      summary: "A thin gold-plated ring topped with a cluster of three cream freshwater pearls.",
    },
  },
  {
    name: "Twisted Rope Bracelet",
    category: "Jewelry",
    price: 1599,
    stock: 28,
    rating: 4.4,
    reviewCount: 308,
    keySpecs: ["925 Sterling silver", "Twisted rope design", "Toggle clasp"],
    description: "A silver twisted rope bracelet with a classic toggle clasp.",
    appearance: {
      primaryColor: "silver",
      details: ["spiral rope texture along the length", "round toggle clasp", "7-inch length"],
      texture: "twisted polished sterling silver",
      styleImpression: "classic, timeless",
      summary: "A sterling silver bracelet with a twisted rope texture and a round toggle clasp.",
    },
  },
  {
    name: "Turquoise Wrap Bracelet",
    category: "Jewelry",
    price: 1799,
    stock: 18,
    rating: 4.5,
    reviewCount: 224,
    keySpecs: ["Natural turquoise", "Multi-wrap cord", "Boho style"],
    description: "A multi-wrap cord bracelet set with small natural turquoise stones.",
    appearance: {
      primaryColor: "turquoise",
      secondaryColors: ["tan"],
      details: ["thin braided cord wraps three times", "small turquoise beads spaced along the cord", "button closure"],
      texture: "waxed cord, smooth polished stones",
      styleImpression: "boho, earthy",
      summary: "A tan braided cord bracelet that wraps three times, dotted with small natural turquoise stones.",
    },
  },
  {
    name: "Art Deco Brooch",
    category: "Jewelry",
    price: 2299,
    stock: 10,
    rating: 4.6,
    reviewCount: 88,
    keySpecs: ["Rhinestone set", "Gold-tone", "Vintage inspired"],
    description: "A fan-shaped Art Deco brooch set with sparkling clear rhinestones.",
    appearance: {
      primaryColor: "gold",
      secondaryColors: ["clear crystal"],
      details: ["geometric fan shape", "rows of pavé rhinestones", "pin back"],
      texture: "polished gold-tone metal, faceted rhinestones",
      styleImpression: "vintage, glamorous",
      summary: "A gold-tone fan-shaped brooch covered in rows of sparkling clear rhinestones.",
    },
  },
  {
    name: "Seed Bead Anklet",
    category: "Jewelry",
    price: 899,
    stock: 40,
    rating: 4.3,
    reviewCount: 415,
    keySpecs: ["Handmade", "Stretch cord", "Multi-colour"],
    description: "A handmade stretch anklet strung with tiny multi-colour seed beads.",
    appearance: {
      primaryColor: "multicolor",
      details: ["tiny seed beads in alternating bright colours", "stretch cord", "no clasp"],
      texture: "smooth glass beads",
      styleImpression: "playful, summer",
      summary: "A bright stretch anklet strung with tiny multicoloured glass seed beads.",
    },
  },

  // ──────────────────────── MEN'S CLOTHING (batch 3) ────────────────────────

  {
    name: "Merino Crew-Neck Sweater",
    category: "Men's Clothing",
    price: 3499,
    stock: 22,
    rating: 4.7,
    reviewCount: 630,
    keySpecs: ["100% Merino wool", "Regular fit", "Machine washable"],
    description: "A warm but lightweight merino crewneck that works over a shirt or on its own.",
    appearance: {
      primaryColor: "burgundy",
      details: ["clean round crew neck", "ribbed cuffs and hem", "no patterns or logos"],
      texture: "smooth fine merino knit",
      styleImpression: "classic, smart-casual",
      summary: "A deep burgundy fine merino crewneck with ribbed cuffs and a clean crew neckline.",
    },
  },
  {
    name: "Slim Chino Trousers",
    category: "Men's Clothing",
    price: 2499,
    stock: 30,
    rating: 4.4,
    reviewCount: 1150,
    keySpecs: ["Stretch cotton", "Slim fit", "Four-pocket"],
    description: "Versatile slim chinos in a stretch cotton that keeps its shape all day.",
    appearance: {
      primaryColor: "olive",
      details: ["flat front", "slim tapered leg", "two side and two back pockets", "no cuffs"],
      texture: "smooth stretch cotton twill",
      styleImpression: "smart-casual, versatile",
      summary: "Olive slim-fit chinos with a flat front, tapered leg and four pockets.",
    },
  },
  {
    name: "Denim Overshirt",
    category: "Men's Clothing",
    price: 2999,
    stock: 18,
    rating: 4.5,
    reviewCount: 488,
    keySpecs: ["100% cotton denim", "Chest pockets", "Wear open or buttoned"],
    description: "A medium-wash denim shirt worn open as a lightweight jacket or buttoned up.",
    appearance: {
      primaryColor: "medium blue",
      details: ["button placket", "two chest patch pockets with buttons", "slightly boxy fit", "long sleeves"],
      texture: "medium-weight woven denim",
      styleImpression: "casual, classic",
      summary: "A medium blue denim overshirt with two chest pockets and a slightly boxy fit.",
    },
  },
  {
    name: "Swim Shorts",
    category: "Men's Clothing",
    price: 1299,
    stock: 45,
    rating: 4.3,
    reviewCount: 820,
    keySpecs: ["Quick-dry fabric", "Side pockets", "Elastic waistband"],
    description: "Quick-drying board shorts with a bold palm-print pattern.",
    appearance: {
      primaryColor: "navy",
      secondaryColors: ["white", "orange"],
      pattern: "tropical palm leaf print",
      details: ["mid-thigh length", "elastic waistband with inner drawcord", "two side pockets", "mesh inner lining"],
      texture: "lightweight quick-dry polyester",
      styleImpression: "holiday, fun",
      summary: "Navy board shorts with an orange and white palm-leaf print, an elasticated waist and mesh lining.",
    },
  },
  {
    name: "Slim Fit Turtleneck",
    category: "Men's Clothing",
    price: 1799,
    stock: 26,
    rating: 4.5,
    reviewCount: 370,
    keySpecs: ["Cotton-modal blend", "Slim fit", "Ribbed turtleneck"],
    description: "A slim ribbed turtleneck in a soft cotton-modal blend.",
    appearance: {
      primaryColor: "black",
      details: ["high ribbed turtle neck", "slim body", "long sleeves", "no logos"],
      texture: "soft ribbed cotton-modal blend",
      styleImpression: "minimal, sleek",
      summary: "A slim black ribbed turtleneck with a high neck and a smooth fitted body.",
    },
  },

  // ──────────────────────── WOMEN'S CLOTHING (batch 3) ────────────────────────

  {
    name: "Satin Pyjama Set",
    category: "Women's Clothing",
    price: 2999,
    stock: 20,
    rating: 4.6,
    reviewCount: 560,
    keySpecs: ["Satin", "Button-up top", "Wide-leg pants"],
    description: "A luxurious satin pyjama set that doubles as loungewear.",
    appearance: {
      primaryColor: "champagne",
      details: ["piped collar and cuffs in contrast trim", "wide-leg pants", "button-front top"],
      texture: "fluid woven satin",
      styleImpression: "luxe, lounge",
      summary: "A champagne satin pyjama set with contrast-piped cuffs and wide-leg trousers.",
    },
  },
  {
    name: "Corset Waistband Belt",
    category: "Women's Clothing",
    price: 1799,
    stock: 24,
    rating: 4.4,
    reviewCount: 295,
    keySpecs: ["Wide corset silhouette", "Lace-up back", "Faux leather"],
    description: "A wide faux leather corset belt that cinches any oversized top or dress.",
    appearance: {
      primaryColor: "black",
      details: ["wide structured band", "lace-up ribbon at the back", "flat busk front closure"],
      texture: "smooth matte faux leather",
      styleImpression: "edgy, structured",
      summary: "A wide black matte faux leather corset belt with a lace-up back and a flat front closure.",
    },
  },
  {
    name: "Ribbed Cardigan",
    category: "Women's Clothing",
    price: 2299,
    stock: 30,
    rating: 4.5,
    reviewCount: 715,
    keySpecs: ["Longline", "Open front", "Soft rib knit"],
    description: "A long open-front cardigan in a chunky rib knit.",
    appearance: {
      primaryColor: "cream",
      details: ["open front with no buttons", "longline length below the hip", "chunky wide rib pattern", "side-seam pockets"],
      texture: "thick chunky rib knit",
      styleImpression: "cosy, effortless",
      summary: "A cream longline open-front chunky rib knit cardigan with side pockets.",
    },
  },
  {
    name: "Tweed Mini Skirt",
    category: "Women's Clothing",
    price: 2799,
    stock: 14,
    rating: 4.6,
    reviewCount: 212,
    keySpecs: ["Boucle tweed", "Gold chain trim", "A-line"],
    description: "A Chanel-inspired boucle tweed mini with a gold chain hem.",
    appearance: {
      primaryColor: "ivory",
      secondaryColors: ["gold", "black"],
      details: ["A-line silhouette", "boucle texture all over", "fine gold chain along the hem", "back zip"],
      texture: "nubby boucle tweed",
      styleImpression: "Parisian, chic",
      summary: "An ivory boucle tweed A-line mini skirt with a fine gold chain running along the hem.",
    },
  },
  {
    name: "Sheer Floral Blouse",
    category: "Women's Clothing",
    price: 1899,
    stock: 26,
    rating: 4.4,
    reviewCount: 388,
    keySpecs: ["Sheer chiffon", "V-neck", "Floral print"],
    description: "A lightweight sheer chiffon blouse in a delicate floral print.",
    appearance: {
      primaryColor: "blush",
      secondaryColors: ["sage", "ivory"],
      pattern: "scattered delicate floral",
      details: ["deep V-neckline", "long sleeves with gathered cuffs", "loose relaxed fit"],
      texture: "sheer lightweight chiffon",
      styleImpression: "feminine, romantic",
      summary: "A sheer blush chiffon blouse with a delicate floral print, deep V-neck and gathered sleeves.",
    },
  },
];

/**
 * The catalog is authored with each product's visual `appearance` already
 * written out, so a blind shopper gets the same detail a sighted one would
 * read off a photo without anything being analysed at request time.
 */
export const SEED_PRODUCTS: ProductSeed[] = PRODUCT_SEED_DATA;

// Out-of-stock products remain visible in search results (LLM sees inStock:
// false) and addToCart() refuses them while offering a real in-stock
// alternative from the same category.
export const OUT_OF_STOCK_NAMES: string[] = SEED_PRODUCTS.filter((p) => p.stock === 0).map((p) => p.name);